# Generated by Django 3.2.7 on 2021-10-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_remove_category_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
