# Generated by Django 3.2.7 on 2021-11-28 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_alter_category_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bread',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='pet.category'),
        ),
    ]
