# Generated by Django 3.2.7 on 2021-12-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_alter_bread_category'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='breeds',
            new_name='breed',
        ),
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(max_length=5000, null=True, unique=True, verbose_name='Department Code'),
        ),
        migrations.AddField(
            model_name='category',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.FileField(null=True, upload_to='images/%Y-%m-%d-%H-%M-%S/department-images/'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=5000),
        ),
    ]
