# Generated by Django 3.2.7 on 2021-11-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kennels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kennel',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name='primary'),
        ),
    ]
