# Generated by Django 3.2.7 on 2021-11-06 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kennels', '0003_alter_kennel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kennel',
            name='breeder',
        ),
    ]
