# Generated by Django 3.2.7 on 2021-12-18 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kennels', '0004_remove_kennel_breeder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kennel',
            name='breed',
        ),
        migrations.AddField(
            model_name='contact',
            name='kennels',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='kennel_contact', to='kennels.kennel'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Breed',
        ),
    ]
