# Generated by Django 3.2.7 on 2021-11-05 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerprofile',
            name='kennel_addres',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='kennel_contact',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='kennel_description',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='kennel_image',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='kennel_name',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='kennel_social',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='kennel_state',
        ),
    ]
