# Generated by Django 3.2.7 on 2021-12-18 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='code',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='district',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.state'),
        ),
    ]
