# Generated by Django 3.2.7 on 2021-12-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_auto_20211218_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='code',
            field=models.IntegerField(),
        ),
    ]
